/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import agents.AStarPlayer;
import agents.Agent;
import agents.AggressivePlayer;
import agents.GreedyPlayer;
import agents.HumanPlayer;
import agents.MinMaxPlayer;
import agents.PacifistPlayer;
import agents.PassivePlayer;
import agents.RealTimeAstartPlayer;
import java.awt.Color;
import riskgame.GamePlay;

/**
 *
 * @author mostafanabil198
 */
public class ChooseAgents extends javax.swing.JFrame {

    int play;
    boolean egypt;
    /**
     * Creates new form ChooseAgents
     */
    public ChooseAgents() {
        initComponents();
    }
    
    public ChooseAgents(int play, boolean egypt) {
        initComponents();
        this.play = play;
        this.egypt = egypt;
        if(play == 1){
            player1lbl.setText("Choose Oppenent");
            player2panel.setVisible(false);
        } else if(play == 2) {
            player1lbl.setText("Choose Player 1");
            player2lbl.setText("Choose Player 2");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        player2panel = new javax.swing.JPanel();
        player2lbl = new javax.swing.JLabel();
        player2select = new javax.swing.JComboBox<String>();
        player1panel = new javax.swing.JPanel();
        player1lbl = new javax.swing.JLabel();
        player1select = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("RISK GAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        player2panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        player2lbl.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        player2lbl.setText("Choose Player");
        player2panel.add(player2lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        player2select.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A* Agent", "Passive Agent", "Aggressive Agent", "Nearly Pacifist Agent", "Greedy Agent", "Realtime A* Agent", "Minimax Agent" }));
        player2panel.add(player2select, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 264, -1));

        getContentPane().add(player2panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 660, 200));

        player1panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        player1lbl.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        player1lbl.setText("Choose Player");
        player1panel.add(player1lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        player1select.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aggressive Agent", "Passive Agent", "Nearly Pacifist Agent", "Greedy Agent", "A* Agent", "Realtime A* Agent", "Minimax Agent" }));
        player1panel.add(player1select, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 264, -1));

        getContentPane().add(player1panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 760, 200));

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        jButton1.setText("Start Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 200, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Agent[] players = new Agent[2];
        if(play == 1){
            players[0] = new HumanPlayer();
            players[1] = getAgent(player1select.getSelectedItem().toString());
        } else if(play == 2) {
            players[0] = getAgent(player1select.getSelectedItem().toString());
            players[1] = getAgent(player2select.getSelectedItem().toString());
        }
        players[0].setColor(Color.ORANGE);
        players[1].setColor(Color.cyan);
        GamePlay.getInstance().setPlayers(players);
        GamePlay.getInstance().assignTerritories();
        this.setVisible(false);
        if(egypt){
            EgyptMap frame = new EgyptMap(play);
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }else{
            USMap frame = new USMap(play);
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private Agent getAgent(String agentName){
        Agent agent = null;
        switch(agentName){
            case "Passive Agent": agent = new PassivePlayer(); break;
            case "Aggressive Agent": agent = new AggressivePlayer(); break;
            case "Nearly Pacifist Agent": agent = new PacifistPlayer(); break;
            case "Greedy Agent": agent = new GreedyPlayer(); break;
            case "A* Agent": agent = new AStarPlayer(); break;
            case "Realtime A* Agent": agent = new RealTimeAstartPlayer(); break;
            case "Minimax Agent": agent = new MinMaxPlayer(); break;
        }
        return agent;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseAgents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseAgents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseAgents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseAgents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseAgents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel player1lbl;
    private javax.swing.JPanel player1panel;
    private javax.swing.JComboBox<String> player1select;
    private javax.swing.JLabel player2lbl;
    private javax.swing.JPanel player2panel;
    private javax.swing.JComboBox<String> player2select;
    // End of variables declaration//GEN-END:variables
}
